 require('basic')
 require('keybindings')
 require('plugins')
 require('colorscheme')

 require('plugin-config.nvim-tree')
 -- require('plugin-config.bufferline')
 require('plugin-config.tabline')
 require('plugin-config.lualine')
 require('plugin-config.telescope')
 require('plugin-config.dashboard')
 require('plugin-config.project')
 require('plugin-config.nvim-treesitter')
 require('plugin-config.indent-blankline')

 require('lsp.setup')
 require('lsp.cmp')
 require('lsp.ui')
 require('lsp.null-ls')

 require('neovide')
